/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registeration;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import sql.SqlLite;

/**
 *
 *
 */
public class RegistrationForm extends javax.swing.JFrame {

    private SqlLite sqlLite;
    private String FirstName;
    private String LastName;
    private String School;
    private String email;
    private JTextComponent editor;
    private boolean shapeR = true;

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        Cinit();
    }

    public final void Cinit() {

        ImageIcon icon = new ImageIcon(this.getClass().getResource("/res/png/ico.png"));
        this.setIconImage(icon.getImage());
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        sqlLite = SqlLite.getInstence();
        startsqlLite();
        editor = ((JTextField) scs.getEditor().getEditorComponent());
        if (scs.getItemCount() != -1) {
            scs.removeAllItems();
        }
        getScList();
        fn.setForeground(Color.lightGray);
        ln.setForeground(Color.lightGray);
        em.setForeground(Color.lightGray);
        showAllR();

    }

    public void startsqlLite() {
        sqlLite.Connect();
    }

    public ImageIcon readResImgicon(String path) {
        ImageIcon icon = null;
        try {

            icon = new ImageIcon(this.getClass().getResource(path));
            //"image/button1.png"
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
        return icon;
    }

    public void getScList() {
        try {
            ResultSet dd = sqlLite.Read_setCommand("select * from sclist");
            while (dd.next()) {
                scs.addItem(dd.getString(1));
            }
            scs.addItem("Other");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Jdiag() {
        jDialog1.setModal(true);
        jDialog1.setSize(300, 120);
        jDialog1.setLocationRelativeTo(scs);
        jDialog1.setVisible(true);
    }

    public void resetA() {

        fn.setEnabled(true);
        ln.setEnabled(true);
        scs.setEnabled(true);
        em.setEnabled(true);
        fn.setText("ex:- jhone");
        ln.setText("ex:- smith");
        scs.setSelectedIndex(0);
        em.setText("ex:- jhonesmith@gmail.com");
        if (fn.getText().equals("ex:- jhone")) {
            fn.setForeground(Color.lightGray);
            jLabel5.setVisible(false);
        }
        if (ln.getText().equals("ex:- smith")) {
            ln.setForeground(Color.lightGray);
            jLabel6.setVisible(false);
        }
        if (em.getText().equals("ex:- jhonesmith@gmail.com")) {
            em.setForeground(Color.lightGray);
            jLabel8.setVisible(false);
        }
        fn.requestFocus();
    }

    public void showAllR() {
        Vector name = new Vector();

        try {
            ResultSet dd = sqlLite.Read_setCommand("select * from reg");
            while (dd.next()) {
                name.add(dd.getString(1) + " " + dd.getString(2) + "         .::ID = " + dd.getString(5));
            }
            jList1.setListData(name);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        nSc = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        scs = new com.jidesoft.swing.AutoCompletionComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jDialog1.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialog1.setResizable(false);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("school :");
        jDialog1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));
        jDialog1.getContentPane().add(nSc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 210, -1));

        jButton6.setText("cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButton8.setText("add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));
        jDialog1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 20, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registeration");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel2.setText("Last Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel3.setText("School :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 41, 20));

        jLabel4.setText("Email :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        fn.setText("ex:- jhone");
        fn.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnFocusLost(evt);
            }
        });
        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnKeyTyped(evt);
            }
        });
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 216, -1));

        ln.setText("ex:- smith");
        ln.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ln.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnFocusLost(evt);
            }
        });
        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnKeyTyped(evt);
            }
        });
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 216, -1));

        em.setText("ex:- jhonesmith@gmail.com");
        em.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        em.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emFocusLost(evt);
            }
        });
        em.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emKeyTyped(evt);
            }
        });
        getContentPane().add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 216, -1));

        scs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scsActionPerformed(evt);
            }
        });
        getContentPane().add(scs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 216, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 20, 20));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 20, 20));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 20, 20));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 20, 20));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 330, 10));

        jButton5.setText("New");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 310, 180));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/png/bk.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 330, 410));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/png/bn.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 80));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("New");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(204, 204, 204));
        jMenu2.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(337, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void scsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scsActionPerformed
        checksc();
    }//GEN-LAST:event_scsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (fn.getText().isEmpty() || fn.getText().equals("ex:- jhone")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        }
        FirstName = fn.getText().toString().toLowerCase();

        if (ln.getText().isEmpty() || ln.getText().equals("ex:- smith")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        }
        LastName = ln.getText().toString().toLowerCase();
        if (scs.getSelectedItem().toString().equals("Other")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        } else if (scs.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        } else {
            School = scs.getSelectedItem().toString();
        }
        if (em.getText().isEmpty() || em.getText().equals("ex:- jhonesmith@gmail.com")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        }
        email = em.getText().toString().toLowerCase();
        if (sqlLite.Write_setCommand("INSERT INTO reg (first_name,last_name,school,email) VALUES( '" + FirstName + "', '" + LastName + "','" + School + "','" + email + "')")) {
            resetA();
            showAllR();
        } else {
            showAllR();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void fnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyTyped
        checkfn();
    }//GEN-LAST:event_fnKeyTyped

    private void lnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyTyped
        checkln();
    }//GEN-LAST:event_lnKeyTyped

    private void emKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emKeyTyped
        checkem();
    }//GEN-LAST:event_emKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        showAllR();
        resetA();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new about.About(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        scs.setSelectedIndex(0);
        checksc();
        jDialog1.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        checksc();
        String sch = nSc.getText().toLowerCase();
        if (sch.isEmpty() || sch.contains("other")) {
            // System.out.println("dsdsds");
        } else {
            if (sqlLite.Write_setCommand("INSERT INTO sclist (name) VALUES('" + nSc.getText() + "')")) {
                scs.removeAllItems();
                getScList();

            } else {
                System.out.println("sdasdsd");
                return;
            }
            scs.setSelectedItem(nSc.getText());
            nSc.setText("");
            jDialog1.dispose();
            checksc();
        }

        // }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showAllR();
        if (jList1.getModel().getSize() != 0) {
            jList1.setSelectedIndex(0);
        } else {
            return;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFocusGained
        fn.setText("");
        fn.setForeground(Color.black);
    }//GEN-LAST:event_fnFocusGained

    private void lnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFocusGained
        ln.setText("");
        ln.setForeground(Color.black);
    }//GEN-LAST:event_lnFocusGained

    private void emFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emFocusGained
        em.setText("");
        em.setForeground(Color.black);
    }//GEN-LAST:event_emFocusGained

    private void fnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFocusLost
        if (fn.getText().isEmpty() || fn.getText().equals("ex:- jhone")) {
            fn.setForeground(Color.lightGray);
            fn.setText("ex:- jhone");
        }
    }//GEN-LAST:event_fnFocusLost

    private void lnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFocusLost
        if (ln.getText().isEmpty() || ln.getText().equals("ex:- smith")) {
            ln.setForeground(Color.lightGray);
            ln.setText("ex:- smith");
        }
    }//GEN-LAST:event_lnFocusLost

    private void emFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emFocusLost
        if (em.getText().isEmpty() || em.getText().equals("ex:- jhonesmith@gmail.com")) {
            em.setForeground(Color.lightGray);
            em.setText("ex:- jhonesmith@gmail.com");
        }
    }//GEN-LAST:event_emFocusLost

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (jList1.getSelectedIndex() == -1) {
            jButton2.setEnabled(true);
        } else {
            fn.setEnabled(false);
            ln.setEnabled(false);
            scs.setEnabled(false);
            em.setEnabled(false);
            jButton2.setEnabled(false);
            String tl = jList1.getSelectedValue().toString().split(".::ID = ")[1];
            try {
                ResultSet dd = sqlLite.Read_setCommand("select * from reg where id= '" + tl + "'");
                while (dd.next()) {
                    fn.setText(dd.getString(1));
                    ln.setText(dd.getString(2));
                    scs.setSelectedItem(dd.getString(3));
                    em.setText(dd.getString(4));
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        showAllR();
        resetA();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        if (jList1.getSelectedIndex() == -1) {
        } else {
            return;
        }

        if (fn.getText().isEmpty() || fn.getText().equals("ex:- jhone")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        }
        FirstName = fn.getText().toString().toLowerCase();

        if (ln.getText().isEmpty() || ln.getText().equals("ex:- smith")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        }
        LastName = ln.getText().toString().toLowerCase();
        if (scs.getSelectedItem().toString().equals("Other")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        } else if (scs.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        } else {
            School = scs.getSelectedItem().toString();
        }
        if (em.getText().isEmpty() || em.getText().equals("ex:- jhonesmith@gmail.com")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details !");
            return;
        }
        email = em.getText().toString().toLowerCase();
        if (sqlLite.Write_setCommand("INSERT INTO reg (first_name,last_name,school,email) VALUES( '" + FirstName + "', '" + LastName + "','" + School + "','" + email + "')")) {
            resetA();
            showAllR();
        } else {
            showAllR();
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String message = " Really Quit ? ";
        String title = "Quit";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String message = " Really Quit ? ";
        String title = "Quit";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing
    public void checkfn() {
        if (fn.getText().isEmpty()) {
            jLabel5.setIcon((Icon) readResImgicon("/res/png/premium.png"));
            jLabel5.setVisible(true);
        } else {
            jLabel5.setIcon((Icon) readResImgicon("/res/png/finished-work.png"));
            jLabel5.setVisible(true);
        }
    }

    public void checkln() {
        if (ln.getText().isEmpty()) {
            jLabel6.setIcon((Icon) readResImgicon("/res/png/premium.png"));
            jLabel6.setVisible(true);
        } else {
            jLabel6.setIcon((Icon) readResImgicon("/res/png/finished-work.png"));
            jLabel6.setVisible(true);
        }
    }

    public void checksc() {
        if (scs.getSelectedIndex() == -1) {
            jLabel7.setIcon((Icon) readResImgicon("/res/png/premium.png"));
            jLabel7.setVisible(true);
            JOptionPane.showMessageDialog(this, "cannot be empty !");
            return;
        } else {
            jLabel7.setIcon((Icon) readResImgicon("/res/png/finished-work.png"));
            jLabel7.setVisible(true);
        }

        if ("Other".equals(scs.getSelectedItem().toString())) {
            jLabel7.setIcon((Icon) readResImgicon("/res/png/premium.png"));
            jLabel7.setVisible(true);
            Jdiag();
            return;
        } else {
            jLabel7.setIcon((Icon) readResImgicon("/res/png/finished-work.png"));
            jLabel7.setVisible(true);
        }

    }

    public void checkem() {
        if (em.getText().isEmpty()) {
            jLabel8.setIcon((Icon) readResImgicon("/res/png/premium.png"));
            jLabel8.setVisible(true);
        } else {
            jLabel8.setIcon((Icon) readResImgicon("/res/png/finished-work.png"));
            jLabel8.setVisible(true);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField nSc;
    protected static com.jidesoft.swing.AutoCompletionComboBox scs;
    // End of variables declaration//GEN-END:variables
}
